#!/usr/bin/bash

# Update Nginx configuration to ensure it runs as nginx user
NGINX_CONF='/etc/nginx/nginx.conf'
sed -i 's/user www-data;/user nginx;/g' $NGINX_CONF
sed -i 's/listen 80 default_server;/listen 0.0.0.0:8080;/g' $NGINX_CONF
nginx -t && nginx -s reload
echo "Nginx has been configured to run as nginx user and listen on 0.0.0.0:8080"
